### ISSUE TITLE
Reduce minium maven version

### ISSUE THREAD

**Issue by MartinWitt** [ASSERT-KTH/terminator#4]
https://github.com/ASSERT-KTH/terminator/blob/5b273d9aa7b8bc796652293ac644167822c1c6f0/fingerprint-generator/pom.xml#L35
With this line to my understandin you require maven 3.9.3+. This will fail on github action runner as they have 3.8.?. For a maven plugin I just copied from other plugins this https://github.com/chains-project/maven-lockfile/blob/main/maven_plugin/pom.xml#L24

**Comment by algomaster99** [comment]
I am not enforcing the version of `maven` here. This is the dependency that contains the classes such as `MavenProject`. I am not sure which maven version is being pulled in, though. See https://github.com/ASSERT-KTH/terminator/actions/runs/5554451854/jobs/10144262746.

**Comment by algomaster99** [comment]
It runs [3.8.8](https://github.com/ASSERT-KTH/terminator/actions/runs/5554620863/jobs/10144640657?pr=6#step:4:9) apparently.
