### ISSUE TITLE
Explore the SYNTHETIC flag for runtime classes

### ISSUE THREAD

**Issue by MartinWitt** [ASSERT-KTH/terminator#61]
https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html

```java
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;

import java.io.IOException;
import java.io.InputStream;

public class SyntheticChecker {
    public static boolean isSyntheticClass(InputStream inputStream) throws IOException {
        ClassReader classReader = new ClassReader(inputStream);
        return (classReader.getAccess() & Opcodes.ACC_SYNTHETIC) != 0;
    }
}
```
Goal: add an option to ignore synthetic classes

**Comment by algomaster99** [comment]
Apparently, `Proxy` classes are not synthetic classes. See https://stackoverflow.com/a/399998.

**Comment by MartinWitt** [comment]
Interesting, but maybe the flag is still useful. If we don't know a class and is synthetic, we could ignore it? Perhaps add a flag for this behavior.

**Comment by algomaster99** [comment]
@MartinWitt I have removed it for now #65. It will help us to detect them in future.
